# 应用服务 WEB 访问端口
server:
  port: 8088

spring:
  application:
    name: sca-service-lottery # 应用名称
  cloud:
    # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
    # Nacos认证信息
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848 # Nacos的服务注册地址，可以配置多个，逗号分隔
        namespace: ce3e435a-4698-42fc-bdbe-c2fd7ed59853 # 命名空间ID，Nacos通过不同的命名空间来区分不同的环境，进行数据隔离，
        service: sca-service-lottery  # 服务注册到Nacos上的名称，一般不用配置
        # nacos客户端向服务端发送心跳的时间间隔，时间单位其实是ms
        heart-beat-interval: 5000
        # 服务端没有接受到客户端心跳请求就将其设为不健康的时间间隔，默认为15s
        # 注：推荐值该值为15s即可，如果有的业务线希望服务下线或者出故障时希望尽快被发现，可以适当减少该值
        heart-beat-timeout: 20000
        metadata:
          mydata: abc   # 元数据部分 - 可以自己随便定制
        # 客户端在启动时是否读取本地配置项(一个文件)来获取服务列表
        # 注：推荐该值为false，若改成true。则客户端会在本地的一个文件中保存服务信息，当下次宕机启动时，会优先读取本地的配置对外提供服务。
        naming-load-cache-at-start: false
        cluster-name: Cluster-A # 创建不同的集群
        group: myGroup # [注意]两个服务如果存在上下游调用关系，必须配置相同的group才能发起访问
        register-enabled: true  # 向注册中心注册服务，默认为true,如果只消费服务，不作为服务提供方，倒是可以设置成false，减少开销
    loadbalancer:
      ribbon:
        enabled: false
feign:
  client:
    config:
      # 全局超时配置
      default:
        # 网络连接阶段1秒超时
        connectTimeout: 1000
        # 服务请求响应阶段5秒超时
        readTimeout: 5000
      # 针对某个特定服务的超时配置
      sca-service-system:
        connectTimeout: 1000
        readTimeout: 2000
